name: Deploy ASP.NET to Custom Server


on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'  # Pas aan op basis van jouw project

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet publish -c Release -o out

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: out

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Wacht op succesvolle build voordat het deployt
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: out

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "out/*"
          target: "/var/www/webapi"

  run:
    runs-on: ubuntu-latest
    needs: deploy  # Wacht tot de deployment klaar is
    steps:
      - name: Restart Server Service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart myapp.service
